# Generated by Django 5.2.5 on 2025-08-18 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trackerAPI.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SAVED", "Saved (not applied)"),
                            ("APPLIED", "Applied"),
                            ("INTERVIEW", "Interviewing"),
                            ("OFFER", "Offer"),
                            ("REJECTED", "Rejected"),
                            ("ACCEPTED", "Accepted"),
                        ],
                        default="SAVED",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                (
                    "remote",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                            ("ONSITE", "On-site"),
                        ],
                        default="ONSITE",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trackerAPI.jobposting",
                    ),
                ),
            ],
        ),
    ]
