# Generated by Django 5.2.5 on 2025-08-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackerAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="date",
            field=models.DateField(),
        ),
    ]
