# Generated by Django 5.2.5 on 2025-08-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trackerAPI", "0002_alter_application_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="additional_steps",
            field=models.BooleanField(default=False),
        ),
    ]
